language: cpp

env:
  - OS_TYPE=centos OS_VERSION=7

services:
  - redis-server

sudo: required
dist: trusty

# Compiler selection
compiler:
  - clang
  - gcc

# Handle git submodules yourself
git:
  submodules: false
# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
  - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
  - git submodule update --init --recursive
  - sudo apt-get update
  - sudo apt-get -y install hiredis-devel libev-devel
  
  # Build steps
script:
  - mkdir build
  - cd build
  - cmake .. && make
