---
# Variable setup.
- name: Include variables
  include_vars: "{{ ansible_os_family }}.yml"

# Setup/install tasks.
- name: Ensure redis is installed.
  yum: name=redis state=installed enablerepo=epel

- name: Ensure Redis is configured.
  template:
    src: redis.conf.j2
    dest: "{{ redis_conf_path }}"
    mode: 0644
  notify: restart redis

- name: Ensure redis is running and enabled on boot.
  service: "name={{ redis_daemon }} state=started enabled=yes"
